### ISSUE TITLE
메인 페이지 개발

### ISSUE THREAD

**Issue by JANGJEEYEON** [JANGJEEYEON/meet_FE#10]
### TODO
- [x] 모임 게시판으로 이동하는 버튼?
- [x] 관리자 버튼 디자인 수정
- [x] 메인 페이지에 들어갈 내용 확정
