### ISSUE TITLE
api 호출 동작 통일

### ISSUE THREAD

**Issue by jomulagy** [JANGJEEYEON/meet_FE#36]
### TODO
- [x] accessToken 확인
- [x] 권한 확인
- [x] 응답 객체 매핑
- [x] 에러 메세지 매핑
- [x] api 호출 함수 server로 모두 변경하기

### 요구사항
- API 호출시 로그인 여부, 권한 인증 여부를 매번 따로 관리 하지 않고, 한번에 관리 하도록 변경
- 응답 객체 처리의 편의성 향상
  - response.data를 반환 함으로써 response.data.data와 같이 호출하지 않도록 변경
  -  200이 아닐경우 에러로 처리하여 response code를 확인해야 하는 번거로움을 해결

### 사용방법
WIKI : [공통 API 호출 함수 사용법](https://github.com/JANGJEEYEON/meet_FE/wiki/%EA%B3%B5%ED%86%B5-API-%ED%98%B8%EC%B6%9C-%ED%95%A8%EC%88%98-%EC%82%AC%EC%9A%A9%EB%B2%95)
