### ISSUE TITLE
footer 리팩토링

### ISSUE THREAD

**Issue by jomulagy** [JANGJEEYEON/meet_FE#45]
### TODO
- [x] footer 기본값 -> 모임 리스트
- [x] 관리자 페이지 버튼 footer로 이동
- [x] 메인 페이지 삭제
