### ISSUE TITLE
투표페이지 수정

### ISSUE THREAD

**Issue by JANGJEEYEON** [JANGJEEYEON/meet_FE#84]
### TODO
- [x] 일정/장소 투표 페이지에서 모임 정보 수정, 삭제 버튼 추가
- [x] 참여여부 투표 페이지에서 모임 정보 수정, 삭제 버튼 추가
- [x] 투표한 사람 확인하는 팝업 개발
